"""Form implementation generated from reading ui file 'Fractals_Mainwindow.ui'

Created by: PyQt6 UI code generator 6.5.2

WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing."""

from PyQt6.QtWidgets import QDialog
from PyQt6 import QtCore, QtGui, QtWidgets
from Interface.UI.Input import Ui_Dialog

class Ui_MainWindow(object):
    """CLass containing methods related to main window of application."""

    def setupUi(self, MainWindow):
        """Method called to build the main window. This method also handles the buttons click event."""
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(464, 191)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 70, 141, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 70, 141, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.clicked)
        self.pushButton_2.clicked.connect(self.clicked_2)

    def retranslateUi(self, MainWindow):
        """Method called to set the proper text in objects of widget."""
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fractals"))
        self.pushButton.setText(_translate("MainWindow", "Mandelbrot Set"))
        self.pushButton_2.setText(_translate("MainWindow", "Julia Set"))

    def clicked(self):
        """Method called to display the widget with input options for Mandelbrot set."""
        self.popup = QDialog()
        self.popup_ui = Ui_Dialog()
        self.popup_ui.setupUi(self.popup, False)
        self.popup.exec()

    def clicked_2(self):
        """Method called to display the widget with input options for Julia set."""
        self.popup = QDialog()
        self.popup_ui = Ui_Dialog()
        self.popup_ui.setupUi(self.popup, True)
        self.popup.exec()