"""Form implementation generated from reading ui file 'Input.ui'

Created by: PyQt6 UI code generator 6.5.2

WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing."""


from PyQt6 import QtCore, QtGui, QtWidgets
from Fractals.Julia import Julia
from Fractals.Mandelbrot import Mandelbrot
from Fractals.Model import Model
from PyQt6.QtWidgets import QDialog
from Interface.UI.Error import Error

class Ui_Dialog(object):
    """CLass containing methods related to widget with input options of application. It also contains the objects of
    classes Model, Julia and Mandelbrot."""
    M = Model()
    Julia = Julia()
    Mandelbrot = Mandelbrot()
    J = True

    def setupUi(self, Dialog, J):
        """Method called to build the widget with input options. This method also handles the button click event."""
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(477, 333)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(40, 40, 161, 131))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 41, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(60, 30, 81, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 80, 81, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 40, 211, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 40, 81, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 80, 81, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 91, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 120, 81, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 160, 81, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 101, 16))
        self.label_6.setObjectName("label_6")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_3.setEnabled(J)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 190, 181, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(70, 30, 81, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 41, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 80, 41, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(70, 80, 81, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(270, 250, 151, 51))
        self.pushButton.setObjectName("pushButton")

        self.J = J
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.clicked)


    def retranslateUi(self, Dialog):
        """Method called to set the proper text in objects of widget. Some texts depend on which fractal is chosen to
        be generated."""
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Resolution"))
        self.label.setText(_translate("Dialog", "Width"))
        self.label_2.setText(_translate("Dialog", "Height"))
        self.lineEdit.setText(_translate("Dialog", "800"))
        self.lineEdit_2.setText(_translate("Dialog", "600"))
        self.groupBox_2.setTitle(_translate("Dialog", "Real and imaginary range"))
        if self.J is True:
            self.lineEdit_3.setText(_translate("Dialog", "-1"))
            self.lineEdit_5.setText(_translate("Dialog", "-1.2"))
            self.lineEdit_6.setText(_translate("Dialog", "1.2"))
        else:
            self.lineEdit_3.setText(_translate("Dialog", "-2"))
            self.lineEdit_5.setText(_translate("Dialog", "-1"))
            self.lineEdit_6.setText(_translate("Dialog", "1"))
        self.label_3.setText(_translate("Dialog", "Real end value"))
        self.lineEdit_4.setText(_translate("Dialog", "1"))
        self.label_4.setText(_translate("Dialog", "Real start value"))
        self.label_5.setText(_translate("Dialog", "Imag end value"))
        self.label_6.setText(_translate("Dialog", "Imag start value"))
        self.groupBox_3.setTitle(_translate("Dialog", "Constant complex number"))
        self.label_7.setText(_translate("Dialog", "C real"))
        self.label_8.setText(_translate("Dialog", "C imag"))
        if self.J is True:
            self.lineEdit_8.setText(_translate("Dialog", "0.01"))
            self.lineEdit_7.setText(_translate("Dialog", "0.285"))
        self.pushButton.setText(_translate("Dialog", "Draw"))

    def clicked(self):
        """Method that sets the variables and calls the proper draw() method when the button is clicked. If the values
        are not correct, it displays the widget with error."""

        w = self.lineEdit.text()
        h = self.lineEdit_2.text()

        rsv = self.lineEdit_3.text()
        rev = self.lineEdit_4.text()
        isv = self.lineEdit_5.text()
        iev = self.lineEdit_6.text()

        cr = self.lineEdit_7.text()
        ci = self.lineEdit_8.text()

        try:
            self.M.set_height(int(h))
            self.M.set_width(int(w))
            self.M.set_re_start(float(rsv))
            self.M.set_re_end(float(rev))
            self.M.set_im_start(float(isv))
            self.M.set_im_end(float(iev))

            if self.J is True:
                self.M.set_c_real(float(cr))
                self.M.set_c_imag(float(ci))
                self.Julia.draw(self.M)
            else:
                self.Mandelbrot.draw(self.M)
        except:
            self.popup = QDialog()
            self.popup_ui = Error()
            self.popup_ui.setupUi(self.popup)
            self.popup.exec()




