"""Form implementation generated from reading ui file 'Error.ui'

Created by: PyQt6 UI code generator 6.5.2

WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing."""


from PyQt6 import QtCore, QtGui, QtWidgets


class Error(object):
    """CLass containing methods related to widget with error message."""

    def setupUi(self, Dialog):
        """Method called to build the widget with error message. This method also handles the button click event."""
        Dialog.setObjectName("Dialog")
        Dialog.resize(272, 122)
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(90, 60, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(40, 30, 211, 20))
        self.label.setObjectName("label")

        self.d = Dialog
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.clicked)

    def retranslateUi(self, Dialog):
        """Method called to set the proper text in objects of widget."""
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Error"))
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.label.setText(_translate("Dialog", "Error - incorrect type of input data"))

    def clicked(self):
        """Method that closes the widget when the button is clicked."""
        self.d.close()
